server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://ep-bold-boat-agwubpn6.c-2.eu-central-1.pg.koyeb.app/koyebdb?

spring.datasource.password=npg_6FCJTnwfGD9z
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.thymeleaf.cache=false
OPENROUTER_API_KEY=${OPENROUTER_API_KEY}


